ame: Ejecutar pagina web

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Configure GitHub Pages
      uses: actions/configure-pages@v3
    
    - name: ejecutar programa
      run: go run ochurus.go