name: Build and Deploy

on:
  push:
    branches:
     - main
jobs:
 build-and-deploy:
    runs-on: "windows-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
         go-version: '1.21.4'
      - name: Instalar dependencias
        run: go get -v ./...
      
      - name: Ejecutar ochurus
        run:  go run -v ./...
      
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
