name: Build and Deploy

on:
  push:
    branches:
     - main
jobs:
 build-and-deploy:
    runs-on: "windows-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: go get -v ./...
      
      - name: Ejecutar ochurus
        run:  go run -v ./...
      
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
