name: Build and Deploy

on:
  push:
    branches:
     - main
jobs:
 build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar dependencias
        uses: go get ochurus.store
      
      - name: Ejecutar ochurus
        uses: go run /private/ochurus.go
      
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3