name: OpenSSH Server for Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install OpenSSH Server
      run: |
        Install-WindowsFeature OpenSSH.Server
        Start-Service sshd
        Set-Service -Name sshd -StartupType 'Automatic'

    - name: Ver ipv4
      run: ipconfig

    - name: Configure OpenSSH
      run: |
        $SecurePassword = ConvertTo-SecureString 'clave-ochurus' -AsPlainText -Force
        Set-LocalUser -Name 'cnlund' -Password $SecurePassword
        New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -PropertyType String -Force

        New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22

        Restart-Service sshd
