name: OpenSSH Server for Windows

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Configure GitHub Pages
      uses: actions/configure-pages@v3

    - name: verificar ip
      run: ip addr show

    - name: abrir server ssh
      run: sudo systemctl start ssh.service

